package oracle.app.cdm.diagram.view.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 22 15:17:24 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartyRelationshipVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PartyRelationshipVORowClient() {
    }

    public Long getPartyId() {
        return (Long) getAttribute("PartyId");
    }

    public void setPartyId(Long value) {
        setAttribute("PartyId", value);
    }

    public String getPartyType() {
        return (String) getAttribute("PartyType");
    }

    public void setPartyType(String value) {
        setAttribute("PartyType", value);
    }

    public String getPartyUniqueName() {
        return (String) getAttribute("PartyUniqueName");
    }

    public void setPartyUniqueName(String value) {
        setAttribute("PartyUniqueName", value);
    }

    public RowID getRowid() {
        return (RowID) getAttribute("Rowid");
    }

    public String getPartyName() {
        return (String) getAttribute("PartyName");
    }

    public void setPartyName(String value) {
        setAttribute("PartyName", value);
    }

    public String getRelationshipCode() {
        return (String) getAttribute("RelationshipCode");
    }

    public void setRelationshipCode(String value) {
        setAttribute("RelationshipCode", value);
    }

    public RowID getRowid1() {
        return (RowID) getAttribute("Rowid1");
    }

    public String getRelationshipType() {
        return (String) getAttribute("RelationshipType");
    }

    public void setRelationshipType(String value) {
        setAttribute("RelationshipType", value);
    }
}

