package oracle.app.cdm.diagram.module;

import oracle.app.cdm.diagram.view.OrganizationDVOImpl;
import oracle.app.cdm.diagram.view.PartiesRelationshipVOImpl;
import oracle.app.cdm.diagram.view.PartyRelationshipVOImpl;

import oracle.app.cdm.diagram.view.PersonDVOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 26 12:05:21 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartyRelationshipAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PartyRelationshipAMImpl() {
    }

    /**
     * Container's getter for PartyRelationshipVO1.
     * @return PartyRelationshipVO1
     */
    public PartyRelationshipVOImpl getPartyRelationshipVO1() {
        return (PartyRelationshipVOImpl) findViewObject("PartyRelationshipVO1");
    }

    /**
     * Container's getter for PartiesRelationshipVO1.
     * @return PartiesRelationshipVO1
     */
    public PartiesRelationshipVOImpl getPartiesRelationshipVO1() {
        return (PartiesRelationshipVOImpl) findViewObject("PartiesRelationshipVO1");
    }

    /**
     * Container's getter for PartyVO1.
     * @return PartyVO1
     */
    public ViewObjectImpl getPartyVO1() {
        return (ViewObjectImpl) findViewObject("PartyVO1");
    }

    /**
     * Container's getter for OrganizationDVO1.
     * @return OrganizationDVO1
     */
    public OrganizationDVOImpl getOrganizationDVO1() {
        return (OrganizationDVOImpl) findViewObject("OrganizationDVO1");
    }

    /**
     * Container's getter for PersonDVO1.
     * @return PersonDVO1
     */
    public PersonDVOImpl getPersonDVO1() {
        return (PersonDVOImpl) findViewObject("PersonDVO1");
    }
}

