package oracle.app.cdm.diagram.view.bc.view;

import java.math.BigInteger;

import oracle.jbo.domain.Array;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 01 16:17:40 IST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiagramGraphNodeRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        id,
        Label,
        Type,
        Attributes;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.id.index();
    public static final int LABEL = AttributesEnum.Label.index();
    public static final int TYPE = AttributesEnum.Type.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DiagramGraphNodeRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute id.
     * @return the id
     */
    public BigInteger getid() {
        return (BigInteger) getAttributeInternal(ID);
    }

    /**
     * Gets the attribute value for the calculated attribute Label.
     * @return the Label
     */
    public String getLabel() {
        return (String) getAttributeInternal(LABEL);
    }

    /**
     * Gets the attribute value for the calculated attribute Type.
     * @return the Type
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute Attributes.
     * @return the Attributes
     */
    public Array getAttributes() {
        return (Array) getAttributeInternal(ATTRIBUTES);
    }
}

