package oracle.app.cdm.diagram.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 28 05:06:57 PDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrganizationDVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OrganizationDVOImpl() {
    }
}

