package oracle.app.cdm.diagram.view;

import java.math.BigDecimal;

import oracle.app.cdm.diagram.view.common.PartiesRelationshipVORow;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 30 12:42:07 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartiesRelationshipVORowImpl extends ViewRowImpl implements PartiesRelationshipVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SubjectId,
        SubjectType,
        SubjectPartyUniqueName,
        SubjectPartyName,
        RelationshipCode,
        SubjectPersonFirstName,
        SubjectPersonMiddleName,
        SubjectPersonLastName,
        SubjectEmailAddress,
        SubjectAddress1,
        SubjectAddress2,
        SubjectAddress3,
        SubjectAddress4,
        SubjectCity,
        SuobjectPostalCode,
        SubjectState,
        SubjectProvince,
        SubjectCountry,
        SubPrimaryPhoneCountryCode,
        SubPrimaryPhoneAreaCode,
        SubPrimaryPhoneNumber,
        SubjectDunsNumber,
        ObjectId,
        ObjectType,
        PObjectType,
        ObjectPartyUniqueName,
        ObjectPartyName,
        ObjectPersonFirstName,
        ObjectPersonMiddleName,
        ObjectPersonLastName,
        ObjectEmailAddress,
        ObjectAddress1,
        ObjectAddress2,
        ObjectAddress3,
        ObjectAddress4,
        ObjectCity,
        ObjectPostalCode,
        ObjectState,
        ObjectProvince,
        ObjectCountry,
        ObjPrimaryPhoneCountryCode,
        ObjPrimaryPhoneAreaCode,
        ObjPrimaryPhoneNumber,
        ObjectDunsNumber,
        Depth;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SUBJECTID = AttributesEnum.SubjectId.index();
    public static final int SUBJECTTYPE = AttributesEnum.SubjectType.index();
    public static final int SUBJECTPARTYUNIQUENAME = AttributesEnum.SubjectPartyUniqueName.index();
    public static final int SUBJECTPARTYNAME = AttributesEnum.SubjectPartyName.index();
    public static final int RELATIONSHIPCODE = AttributesEnum.RelationshipCode.index();
    public static final int SUBJECTPERSONFIRSTNAME = AttributesEnum.SubjectPersonFirstName.index();
    public static final int SUBJECTPERSONMIDDLENAME = AttributesEnum.SubjectPersonMiddleName.index();
    public static final int SUBJECTPERSONLASTNAME = AttributesEnum.SubjectPersonLastName.index();
    public static final int SUBJECTEMAILADDRESS = AttributesEnum.SubjectEmailAddress.index();
    public static final int SUBJECTADDRESS1 = AttributesEnum.SubjectAddress1.index();
    public static final int SUBJECTADDRESS2 = AttributesEnum.SubjectAddress2.index();
    public static final int SUBJECTADDRESS3 = AttributesEnum.SubjectAddress3.index();
    public static final int SUBJECTADDRESS4 = AttributesEnum.SubjectAddress4.index();
    public static final int SUBJECTCITY = AttributesEnum.SubjectCity.index();
    public static final int SUOBJECTPOSTALCODE = AttributesEnum.SuobjectPostalCode.index();
    public static final int SUBJECTSTATE = AttributesEnum.SubjectState.index();
    public static final int SUBJECTPROVINCE = AttributesEnum.SubjectProvince.index();
    public static final int SUBJECTCOUNTRY = AttributesEnum.SubjectCountry.index();
    public static final int SUBPRIMARYPHONECOUNTRYCODE = AttributesEnum.SubPrimaryPhoneCountryCode.index();
    public static final int SUBPRIMARYPHONEAREACODE = AttributesEnum.SubPrimaryPhoneAreaCode.index();
    public static final int SUBPRIMARYPHONENUMBER = AttributesEnum.SubPrimaryPhoneNumber.index();
    public static final int SUBJECTDUNSNUMBER = AttributesEnum.SubjectDunsNumber.index();
    public static final int OBJECTID = AttributesEnum.ObjectId.index();
    public static final int OBJECTTYPE = AttributesEnum.ObjectType.index();
    public static final int POBJECTTYPE = AttributesEnum.PObjectType.index();
    public static final int OBJECTPARTYUNIQUENAME = AttributesEnum.ObjectPartyUniqueName.index();
    public static final int OBJECTPARTYNAME = AttributesEnum.ObjectPartyName.index();
    public static final int OBJECTPERSONFIRSTNAME = AttributesEnum.ObjectPersonFirstName.index();
    public static final int OBJECTPERSONMIDDLENAME = AttributesEnum.ObjectPersonMiddleName.index();
    public static final int OBJECTPERSONLASTNAME = AttributesEnum.ObjectPersonLastName.index();
    public static final int OBJECTEMAILADDRESS = AttributesEnum.ObjectEmailAddress.index();
    public static final int OBJECTADDRESS1 = AttributesEnum.ObjectAddress1.index();
    public static final int OBJECTADDRESS2 = AttributesEnum.ObjectAddress2.index();
    public static final int OBJECTADDRESS3 = AttributesEnum.ObjectAddress3.index();
    public static final int OBJECTADDRESS4 = AttributesEnum.ObjectAddress4.index();
    public static final int OBJECTCITY = AttributesEnum.ObjectCity.index();
    public static final int OBJECTPOSTALCODE = AttributesEnum.ObjectPostalCode.index();
    public static final int OBJECTSTATE = AttributesEnum.ObjectState.index();
    public static final int OBJECTPROVINCE = AttributesEnum.ObjectProvince.index();
    public static final int OBJECTCOUNTRY = AttributesEnum.ObjectCountry.index();
    public static final int OBJPRIMARYPHONECOUNTRYCODE = AttributesEnum.ObjPrimaryPhoneCountryCode.index();
    public static final int OBJPRIMARYPHONEAREACODE = AttributesEnum.ObjPrimaryPhoneAreaCode.index();
    public static final int OBJPRIMARYPHONENUMBER = AttributesEnum.ObjPrimaryPhoneNumber.index();
    public static final int OBJECTDUNSNUMBER = AttributesEnum.ObjectDunsNumber.index();
    public static final int DEPTH = AttributesEnum.Depth.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PartiesRelationshipVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectId.
     * @return the SubjectId
     */
    public Long getSubjectId() {
        return (Long) getAttributeInternal(SUBJECTID);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectType.
     * @return the SubjectType
     */
    public String getSubjectType() {
        return (String) getAttributeInternal(SUBJECTTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectPartyUniqueName.
     * @return the SubjectPartyUniqueName
     */
    public String getSubjectPartyUniqueName() {
        return (String) getAttributeInternal(SUBJECTPARTYUNIQUENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectPartyName.
     * @return the SubjectPartyName
     */
    public String getSubjectPartyName() {
        return (String) getAttributeInternal(SUBJECTPARTYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute RelationshipCode.
     * @return the RelationshipCode
     */
    public String getRelationshipCode() {
        return (String) getAttributeInternal(RELATIONSHIPCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectPersonFirstName.
     * @return the SubjectPersonFirstName
     */
    public String getSubjectPersonFirstName() {
        return (String) getAttributeInternal(SUBJECTPERSONFIRSTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectPersonMiddleName.
     * @return the SubjectPersonMiddleName
     */
    public String getSubjectPersonMiddleName() {
        return (String) getAttributeInternal(SUBJECTPERSONMIDDLENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectPersonLastName.
     * @return the SubjectPersonLastName
     */
    public String getSubjectPersonLastName() {
        return (String) getAttributeInternal(SUBJECTPERSONLASTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectEmailAddress.
     * @return the SubjectEmailAddress
     */
    public String getSubjectEmailAddress() {
        return (String) getAttributeInternal(SUBJECTEMAILADDRESS);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectAddress1.
     * @return the SubjectAddress1
     */
    public String getSubjectAddress1() {
        return (String) getAttributeInternal(SUBJECTADDRESS1);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectAddress2.
     * @return the SubjectAddress2
     */
    public String getSubjectAddress2() {
        return (String) getAttributeInternal(SUBJECTADDRESS2);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectAddress3.
     * @return the SubjectAddress3
     */
    public String getSubjectAddress3() {
        return (String) getAttributeInternal(SUBJECTADDRESS3);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectAddress4.
     * @return the SubjectAddress4
     */
    public String getSubjectAddress4() {
        return (String) getAttributeInternal(SUBJECTADDRESS4);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectCity.
     * @return the SubjectCity
     */
    public String getSubjectCity() {
        return (String) getAttributeInternal(SUBJECTCITY);
    }

    /**
     * Gets the attribute value for the calculated attribute SuobjectPostalCode.
     * @return the SuobjectPostalCode
     */
    public String getSuobjectPostalCode() {
        return (String) getAttributeInternal(SUOBJECTPOSTALCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectState.
     * @return the SubjectState
     */
    public String getSubjectState() {
        return (String) getAttributeInternal(SUBJECTSTATE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectProvince.
     * @return the SubjectProvince
     */
    public String getSubjectProvince() {
        return (String) getAttributeInternal(SUBJECTPROVINCE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectCountry.
     * @return the SubjectCountry
     */
    public String getSubjectCountry() {
        return (String) getAttributeInternal(SUBJECTCOUNTRY);
    }

    /**
     * Gets the attribute value for the calculated attribute SubPrimaryPhoneCountryCode.
     * @return the SubPrimaryPhoneCountryCode
     */
    public String getSubPrimaryPhoneCountryCode() {
        return (String) getAttributeInternal(SUBPRIMARYPHONECOUNTRYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubPrimaryPhoneAreaCode.
     * @return the SubPrimaryPhoneAreaCode
     */
    public String getSubPrimaryPhoneAreaCode() {
        return (String) getAttributeInternal(SUBPRIMARYPHONEAREACODE);
    }

    /**
     * Gets the attribute value for the calculated attribute SubPrimaryPhoneNumber.
     * @return the SubPrimaryPhoneNumber
     */
    public String getSubPrimaryPhoneNumber() {
        return (String) getAttributeInternal(SUBPRIMARYPHONENUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute SubjectDunsNumber.
     * @return the SubjectDunsNumber
     */
    public String getSubjectDunsNumber() {
        return (String) getAttributeInternal(SUBJECTDUNSNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectId.
     * @return the ObjectId
     */
    public Long getObjectId() {
        return (Long) getAttributeInternal(OBJECTID);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectType.
     * @return the ObjectType
     */
    public String getObjectType() {
        return (String) getAttributeInternal(OBJECTTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute PObjectType.
     * @return the PObjectType
     */
    public String getPObjectType() {
        return (String) getAttributeInternal(POBJECTTYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectPartyUniqueName.
     * @return the ObjectPartyUniqueName
     */
    public String getObjectPartyUniqueName() {
        return (String) getAttributeInternal(OBJECTPARTYUNIQUENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectPartyName.
     * @return the ObjectPartyName
     */
    public String getObjectPartyName() {
        return (String) getAttributeInternal(OBJECTPARTYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectPersonFirstName.
     * @return the ObjectPersonFirstName
     */
    public String getObjectPersonFirstName() {
        return (String) getAttributeInternal(OBJECTPERSONFIRSTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectPersonMiddleName.
     * @return the ObjectPersonMiddleName
     */
    public String getObjectPersonMiddleName() {
        return (String) getAttributeInternal(OBJECTPERSONMIDDLENAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectPersonLastName.
     * @return the ObjectPersonLastName
     */
    public String getObjectPersonLastName() {
        return (String) getAttributeInternal(OBJECTPERSONLASTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectEmailAddress.
     * @return the ObjectEmailAddress
     */
    public String getObjectEmailAddress() {
        return (String) getAttributeInternal(OBJECTEMAILADDRESS);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectAddress1.
     * @return the ObjectAddress1
     */
    public String getObjectAddress1() {
        return (String) getAttributeInternal(OBJECTADDRESS1);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectAddress2.
     * @return the ObjectAddress2
     */
    public String getObjectAddress2() {
        return (String) getAttributeInternal(OBJECTADDRESS2);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectAddress3.
     * @return the ObjectAddress3
     */
    public String getObjectAddress3() {
        return (String) getAttributeInternal(OBJECTADDRESS3);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectAddress4.
     * @return the ObjectAddress4
     */
    public String getObjectAddress4() {
        return (String) getAttributeInternal(OBJECTADDRESS4);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectCity.
     * @return the ObjectCity
     */
    public String getObjectCity() {
        return (String) getAttributeInternal(OBJECTCITY);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectPostalCode.
     * @return the ObjectPostalCode
     */
    public String getObjectPostalCode() {
        return (String) getAttributeInternal(OBJECTPOSTALCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectState.
     * @return the ObjectState
     */
    public String getObjectState() {
        return (String) getAttributeInternal(OBJECTSTATE);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectProvince.
     * @return the ObjectProvince
     */
    public String getObjectProvince() {
        return (String) getAttributeInternal(OBJECTPROVINCE);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectCountry.
     * @return the ObjectCountry
     */
    public String getObjectCountry() {
        return (String) getAttributeInternal(OBJECTCOUNTRY);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjPrimaryPhoneCountryCode.
     * @return the ObjPrimaryPhoneCountryCode
     */
    public String getObjPrimaryPhoneCountryCode() {
        return (String) getAttributeInternal(OBJPRIMARYPHONECOUNTRYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjPrimaryPhoneAreaCode.
     * @return the ObjPrimaryPhoneAreaCode
     */
    public String getObjPrimaryPhoneAreaCode() {
        return (String) getAttributeInternal(OBJPRIMARYPHONEAREACODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjPrimaryPhoneNumber.
     * @return the ObjPrimaryPhoneNumber
     */
    public String getObjPrimaryPhoneNumber() {
        return (String) getAttributeInternal(OBJPRIMARYPHONENUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute ObjectDunsNumber.
     * @return the ObjectDunsNumber
     */
    public String getObjectDunsNumber() {
        return (String) getAttributeInternal(OBJECTDUNSNUMBER);
    }

    /**
     * Gets the attribute value for the calculated attribute Depth.
     * @return the Depth
     */
    public BigDecimal getDepth() {
        return (BigDecimal) getAttributeInternal(DEPTH);
    }
}

