package oracle.app.cdm.diagram.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 28 04:18:04 PDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PersonDVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PersonDVOImpl() {
    }

    /**
     * Returns the bind variable value for BindUserPartyId.
     * @return bind variable value for BindUserPartyId
     */
    public Long getBindUserPartyId() {
        return (Long) getNamedWhereClauseParam("BindUserPartyId");
    }

    /**
     * Sets <code>value</code> for bind variable BindUserPartyId.
     * @param value value to bind as BindUserPartyId
     */
    public void setBindUserPartyId(Long value) {
        setNamedWhereClauseParam("BindUserPartyId", value);
    }
}

