package oracle.app.cdm.diagram.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 22 15:17:24 IST 2012
// ---------------------------------------------------------------------
public interface PartyRelationshipVORow extends Row {


    String getPartyType();

    void setPartyType(String value);

    String getPartyUniqueName();

    void setPartyUniqueName(String value);

    RowID getRowid();

    String getPartyName();

    void setPartyName(String value);

    String getRelationshipCode();

    void setRelationshipCode(String value);

    RowID getRowid1();


}

