package oracle.app.cdm.diagram.view.common;

import java.math.BigDecimal;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 14 00:56:20 PST 2012
// ---------------------------------------------------------------------
public interface PartiesRelationshipVORow extends Row {
    Long getSubjectId();

    String getSubjectType();

    String getSubjectPartyUniqueName();

    String getSubjectPartyName();

    String getRelationshipCode();

    Long getObjectId();

    String getObjectType();

    String getPObjectType();

    String getObjectPartyUniqueName();

    String getObjectPartyName();

    BigDecimal getDepth();
}

